### PR TITLE
perf: optimized image assets

### PR DESCRIPTION
**Pull request by tiagofilipesilva**
This PR optimizes some image assets in without quality loss.

### CODE REVIEW

**Comment by doomspork** [comment]
Wow thank you @tiagofilipesilva! This is awesome. The team is going to pull this down, take a look, and if all systems are a go we'll get this merged and deployed :tada:

**Comment by btkostner** [comment]
@tiagofilipesilva Thank you for the PR! We do use an image optimization plugin called [@aceforth/nuxt-optimized-images](https://github.com/juliomrqz/nuxt-optimized-images) during the website build process, so the images served at [pop.system76.com](https://pop.system76.com) are much more optimized than what we store in the repository. We also lazy load most of the images to improve performance.

Thank you for your time on this, but in case the design changes, it's best if we keep the original assets in the repository.

**Comment by tiagofilipesilva** [comment]
Hi to all! I know about your optimizers, but these sizes are smaller than what your optimizer provides, with the exception of a couple assets, but I believe I did not touch those.

Do you mind if I optimize the assets for popsicle _et al_ used in Pop!OS?

Thanks and keep up the good work!

**Comment by btkostner** [comment]
Ping @isantop ^

**Pull request closed without merging**
