### PR TITLE
Remove Scrollbars from download component

### PR DESCRIPTION
**Pull request by CannedShroud**

### CODE REVIEW

**Comment by burden** [comment]
Thanks for the PR @CannedShroud. I pulled it down to test but truth be told, I wasn't able to get erroneous scrollbars to render on the page before your changes. Could you let me know under what conditions you ran into the scroll bars?

**Comment by doomspork** [comment]
Howdy @CannedShroud I just wanted to follow-up on this. Did you have a chance to look over @burden's comment above? We'd like to reproduce the issue before merging in changes :+1:

**Comment by CannedShroud** [comment]
Sorry for the late reply. Was away from my PC for a bit. As for the issue, I guess it was a error from my end and I am not able to recreate it. Sorry : (

**Comment by doomspork** [comment]
No need to apologize @CannedShroud, we appreciate it! Hope you are safe and well. Thanks again :tada:

**Pull request closed without merging**
